---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: schedule
    trigger: true
  - get: git-repo
  - put: docker-image
    params:
      build: git-repo/ci

resources:
- name: schedule
  type: time
  source:
    interval: 24h
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

- name: git-repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

- name: docker-image
  type: docker-image
  source:
    email: ((docker_hub_email))
    username: ((docker_hub_username))
    password: ((docker_hub_password))
    repository: ((docker_hub_repository))
